<?php
$z[0]=Array("arcurl","",124,139);
$z[1]=Array("title","",164,178);
$z[2]=Array("title","",180,194);
$z[3]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<img src='{@me['litpic']}'/>\"); ",198,320);
$z[3][4]['runphp']="yes";
$z[4]=Array("yuyan","",352,366);
$z[5]=Array("daxiao","",389,404);
$z[6]=Array("pubdate","",427,474);
$z[6][4]['function']="Mydate('Y-m-d',@me)";
$z[7]=Array("arcurl","",513,528);

?>