<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:yuyan itemname="软件语言" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="简体中文"  maxlength="250" page="">
</field:yuyan>
<field:daxiao itemname="软件大小" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:daxiao>
<field:huanjing itemname="适用环境" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="全新系统"  maxlength="250" page="">
</field:huanjing>
<field:md5xy itemname="MD5校检" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:md5xy>
<field:xldx itemname="[迅雷]电信" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:xldx>
<field:dxxlhy itemname="电信迅雷会员" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:dxxlhy>
<field:dx1 itemname="电信下载①" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:dx1>
<field:dx2 itemname="电信下载②" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:dx2>
<field:xlwt itemname="[迅雷]网通" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:xlwt>
<field:wtxlhy itemname="网通迅雷会员" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:wtxlhy>
<field:wt1 itemname="网通下载①" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:wt1>
<field:wt2 itemname="网通下载②" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:wt2>
<field:azbz itemname="安装步骤" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="1000" page="">
</field:azbz>
