<?php
$z[0]=Array("global","",66,98);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("field","@me=(@me==1)?'style=\"color:#fe020e;\"':'';",498,591);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("field","@me=(@me==7)?'style=\"color:#fe020e;\"':'';",638,731);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("field","@me=(@me==44)?'style=\"color:#fe020e;\"':'';",780,874);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";

?>