<?php
$z[0]=Array("global","",293,321);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",334,357);
$z[1][4]['name']="seotitle";
$z[2]=Array("field","",398,421);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",461,519);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",537,569);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",637,672);
$z[5][4]['filename']="head.htm";
$z[6]=Array("global","",793,825);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("list","\r\n<li>\r\n<div class=\"new-ghost-img\"><img src=\"/images/defaultpic.gif\" /></div>\r\n<div class=\"new-ghost-info\">\r\n<strong><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a>[field:array runphp='yes']@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<img src='{@me['litpic']}'/>\"); [/field:array]</strong><br />\r\n软件语言：[field:yuyan/]<br />\r\n软件大小：[field:daxiao/]<br />\r\n发布日期：[field:pubdate function=\"Mydate('Y-m-d',@me)\"/]<br />\r\n<div class=\"download\"><a href=\"[field:arcurl/]\" target=\"_blank\">立即下载</a></div>\r\n</div>\r\n</li>\r\n",960,1583);
$z[7][4]['pagesize']="8";
$z[8]=Array("pagelist","",1651,1736);
$z[8][4]['pagelang']="cn";
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="2";
$z[9]=Array("include","",1754,1790);
$z[9][4]['filename']="right.htm";
$z[10]=Array("include","",1836,1873);
$z[10][4]['filename']="footer.htm";

?>