<?php
$z[0]=Array("global","",32,64);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("arclist","\r\n<li><a style=\"text-decoration:none;\" href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></li>\r\n",128,347);
$z[1][4]['typeid']="45";
$z[1][4]['row']="8";
$z[1][4]['titlelen']="200";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="desc";
$z[2]=Array("global","",366,398);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></li>\r\n",499,688);
$z[3][4]['typeid']="44";
$z[3][4]['row']="9";
$z[3][4]['titlelen']="200";
$z[3][4]['orderby']="id";
$z[3][4]['orderway']="desc";

?>